### ISSUE TITLE
Is there an example of caching the public key

### ISSUE THREAD

**Issue by ahmadabdul3** [auth0-samples/auth0-rubyonrails-api-samples#12]
Requests to my API are taking close to 1 second/request. Is it ok to save the public key somewhere so I don't hit the Auth0 service every time? Is there an example of caching the public key?

Also, if the public key is saved, how often/when should it be updated?

Thanks

**Comment by robwise** [comment]
This is a very good question, I would love to know the answer to this as well.

**Comment by robwise** [comment]
@ahmadabdul3 I just found this in the community forum: https://community.auth0.com/questions/6067/when-do-signing-certificates-changeexpire

No example yet, but it seems they recommend caching it, then checking if it changed only if a JWT fails to pass verification just in case the public key changed for some reason.

**Comment by aaguiarz** [comment]
Hi, yes, that's the approach we recommend. 

If for whatever reason the key needs to be changed, your cache will be invalid. We could provide 'If-Modified-Since' conditional requests, but from your side it will still imply making an http request every time, so it's better to just ask for it again if verification fails.
